openapi: 3.0.3
info:
  title: Workout Tracker API
  version: 1.0.0
  description: API documentation for the workout tracker backend
servers:
  - url: http://localhost:4000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /users/signup:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User created
        "400":
          description: Invalid input

  /users/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Unauthorized

  /workouts:
    get:
      summary: Get all workouts for the logged in user
      security:
        - bearerAuth: []
      parameters:
        - name: is_completed
          in: query
          schema:
            type: boolean
          description: Filter by workout completion status
      responses:
        "200":
          description: List of workouts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    workout_id:
                      type: integer
                    scheduled_date:
                      type: string
                      format: date

  /workouts/generateReport/{workout_id}:
    get:
      summary: Get a workout by ID
      security:
        - bearerAuth: []
      parameters:
        - name: workout_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the workout
      responses:
        "200":
          description: A single workout
          content:
            application/json:
              schema:
                type: object
                properties:
                  workout_id:
                    type: integer
                  scheduled_date:
                    type: string
                    format: date
