--
-- PostgreSQL database dump
--

\restrict 4y4XyuVK7I3s5bs1dHlwaeRJR4aITfv7ONCur1tY49i5HEVWTWn8n11AtbQwxqm

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-09-15 23:49:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16396)
-- Name: exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercises (
    exercise_id integer NOT NULL,
    name character varying(50),
    muscle_group character varying(50)
);


ALTER TABLE public.exercises OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16395)
-- Name: exercises_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercises ALTER COLUMN exercise_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16414)
-- Name: sets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sets (
    set_id integer NOT NULL,
    workout_exercise_id integer,
    reps integer,
    weight integer,
    comment text
);


ALTER TABLE public.sets OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16413)
-- Name: sets_set_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sets ALTER COLUMN set_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sets_set_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    name character varying(50),
    email character varying(255),
    password_hash character varying(100)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16408)
-- Name: workout_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_exercises (
    workout_exercise_id integer NOT NULL,
    workout_id integer,
    exercise_id integer,
    order_in integer
);


ALTER TABLE public.workout_exercises OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16407)
-- Name: workout_exercises_workout_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workout_exercises ALTER COLUMN workout_exercise_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_exercises_workout_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16402)
-- Name: workouts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workouts (
    workout_id integer NOT NULL,
    user_id integer,
    scheduled_date timestamp without time zone,
    is_completed boolean DEFAULT false NOT NULL
);


ALTER TABLE public.workouts OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16401)
-- Name: workouts_workout_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workouts ALTER COLUMN workout_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workouts_workout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4766 (class 2606 OID 16400)
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (exercise_id);


--
-- TOC entry 4772 (class 2606 OID 16420)
-- Name: sets sets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sets
    ADD CONSTRAINT sets_pkey PRIMARY KEY (set_id);


--
-- TOC entry 4764 (class 2606 OID 16394)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4770 (class 2606 OID 16412)
-- Name: workout_exercises workout_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_exercises
    ADD CONSTRAINT workout_exercises_pkey PRIMARY KEY (workout_exercise_id);


--
-- TOC entry 4768 (class 2606 OID 16406)
-- Name: workouts workouts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workouts
    ADD CONSTRAINT workouts_pkey PRIMARY KEY (workout_id);


--
-- TOC entry 4776 (class 2606 OID 16468)
-- Name: sets sets_workout_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sets
    ADD CONSTRAINT sets_workout_exercise_id_fkey FOREIGN KEY (workout_exercise_id) REFERENCES public.workout_exercises(workout_exercise_id) ON DELETE CASCADE;


--
-- TOC entry 4774 (class 2606 OID 16431)
-- Name: workout_exercises workout_exercises_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_exercises
    ADD CONSTRAINT workout_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id);


--
-- TOC entry 4775 (class 2606 OID 16463)
-- Name: workout_exercises workout_exercises_workout_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_exercises
    ADD CONSTRAINT workout_exercises_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(workout_id) ON DELETE CASCADE;


--
-- TOC entry 4773 (class 2606 OID 16421)
-- Name: workouts workouts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workouts
    ADD CONSTRAINT workouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


-- Completed on 2025-09-15 23:49:38

--
-- PostgreSQL database dump complete
--

\unrestrict 4y4XyuVK7I3s5bs1dHlwaeRJR4aITfv7ONCur1tY49i5HEVWTWn8n11AtbQwxqm

